services:
  - type: web
    name: smart-boda-admin
    env: node
    buildCommand: cd admin-console && npm install && npm run build
    startCommand: cd admin-console && npm start
    envVars:
      - key: NODE_ENV
        value: production