services:
  - type: web
    name: smart-boda-admin
    env: node
    plan: free
    buildCommand: npm cache clean --force && npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
